### ISSUE TITLE
problem 

### ISSUE THREAD

**Issue by datseismo** [polimi-ispl/deep_prior_interpolation#4]
Hii deep_prior_interplation developer, While running the second example i am getting error like T.build_input(imgshape)
TypeError: build_input() takes 1 positional argument but 2 were given, however i get  The image shape is (512, 128, 128, 1) .Please suggest a solution.Thanks.

**Comment by fpicetti** [comment]
Hi @datseismo , which notebook you are referring to?
We were re-organizing our repo as we spotted some inconsistencies between different versions. Can you please try it now?

**Comment by datseismo** [comment]
Tanks for your response. I want to reconstruct my 2d seismic data using the code proof_of_concept.ipynb...I will try and let you know.

**Comment by datseismo** [comment]
What kind of repository it is ?? A lot of bugs?

**Comment by datseismo** [comment]
Yes sir, I tried it, it runs fine now.Thanks.

**Comment by fpicetti** [comment]
Ok then.
Just let me reply to your previous (deleted) comment:

> What kind of repository it is ?? A lot of bugs?

This is a repository made by researchers for researchers; its main goal is to share ideas.
**This means that it could be slow, non-optimized, and written for non experts**.

Regarding bugs: it's kind of impossible to write a research code without bugs. Especially if the team is made by a few people.
"Lots of bugs" are the results of lot of works; I appreciated that you helped me spotting them out, but please calm down.

Regarding your doubts and [struggles](https://github.com/polimi-ispl/deep_prior_interpolation/issues/5), I am happy you started a PhD on machine learning, but it is your path. In general, you should learn how to find the answer to your question, autonomously, before asking rudely to other researchers.

All the bests.
